// Generated by CoffeeScript 1.6.3
(function() {
  var DbDal, app, express, http, path, _ref;

  express = require('express');

  path = require('path');

  http = require('http');

  app = express();

  app.set('port', (_ref = process.env.PORT) != null ? _ref : 80);

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'ejs');

  app.use(express.favicon());

  app.use(express.logger('dev'));

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(express["static"](path.join(__dirname, 'public')));

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  DbDal = require('./lib/dal/DbDal');

  new DbDal.MongoDB().connect();

  (new (require('./lib/routes/NameRoute'))(app)).addRequestHandlers();

  (new (require('./lib/routes/AdminRoute'))(app)).addRequestHandlers();

  http.createServer(app).listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

}).call(this);
