// Generated by CoffeeScript 1.6.3
(function() {
  var DbDal, NameCandidate, NameRoute, NameSrc, async, util, _;

  _ = require('underscore');

  async = require('async');

  util = require('util');

  DbDal = require('../dal/DbDal');

  NameCandidate = DbDal.NameCandidate;

  NameSrc = DbDal.NameSrc;

  module.exports = NameRoute = (function() {
    function NameRoute(app) {
      this.app = app;
    }

    NameRoute.prototype.addRequestHandlers = function() {
      this.app.get('/', _.bind(this.handleIndex, this));
      this.app.get('/sysInit', _.bind(this.handleSysInit, this));
      this.app.get('/voter/login', _.bind(this.handleVotorLogin, this));
      this.app.get('/:voter/vote', _.bind(this.handleVoterVote, this));
      return this.app.get('/:voter/voteFor', _.bind(this.handleVoterVoteFor, this));
    };

    NameRoute.prototype.handleIndex = function(req, res) {
      return res.redirect(301, "/voter/login");
    };

    NameRoute.prototype.handleSysInit = function(req, res) {
      var _this = this;
      return async.waterfall([
        function(cb) {
          return _this.__dropTables(cb);
        }, function(err, cb) {
          return _this.__generateCandidateNames(cb);
        }
      ], function(err) {
        if (err) {
          return res.send(500);
        } else {
          return res.render('page_sys_init');
        }
      });
    };

    NameRoute.prototype.__dropTables = function(cb) {
      var clearTableRoutins;
      clearTableRoutins = [
        function(cb) {
          return NameCandidate.remove({}, cb);
        }, function(cb) {
          return NameSrc.remove({}, cb);
        }
      ];
      return async.parallel(clearTableRoutins, cb);
    };

    NameRoute.prototype.__generateCandidateNames = function(cb) {
      var candidates, iterator, nameSrcs, namesrc, source;
      nameSrcs = [];
      namesrc = new NameSrc();
      namesrc.secondWordList = '业勤祺敬粲禀渠汇载钰琛煜歆炜盟睦靖焕鼎庄园诗圣群诠'.split('');
      namesrc.thirdWordList = '森茜茗理婷腆然迪登尧雅勋翔岚凯富堡超越'.split('');
      nameSrcs.push(namesrc);
      namesrc = new NameSrc();
      namesrc.secondWordList = '蕾辞韬丽'.split('');
      namesrc.thirdWordList = '竹任百光'.split('');
      nameSrcs.push(namesrc);
      candidates = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = nameSrcs.length; _i < _len; _i++) {
          source = nameSrcs[_i];
          _results.push(source.genNameCandidates());
        }
        return _results;
      })();
      candidates = _.chain(candidates).flatten().uniq().value();
      iterator = function(candidate, callback) {
        var nameCandidate;
        nameCandidate = new NameCandidate();
        nameCandidate.name = candidate;
        console.log(nameCandidate);
        return nameCandidate.save(callback);
      };
      return async.forEach(candidates, iterator, cb);
    };

    NameRoute.prototype.handleVotorLogin = function(req, res) {
      var voters;
      voters = [
        {
          displayName: '熊猫'
        }, {
          displayName: '云'
        }, {
          displayName: '一苇渡江'
        }
      ];
      return res.render('page_voter_login', {
        voters: voters
      });
    };

    NameRoute.prototype.handleVoterVote = function(req, res) {
      var voter;
      voter = req.params.voter;
      return this.__getCandidateNamesFromDb(voter, function(err, results) {
        return res.render('page_voter_vote.ejs', {
          voter: voter,
          nameCandidates: results
        });
      });
    };

    NameRoute.prototype.__getCandidateNamesFromDb = function(voter, cb) {
      return NameCandidate.find(null, null, {
        sort: {
          name: 1
        }
      }, function(err, docs) {
        var name, results, score, simpleName, _i, _len, _ref;
        results = {
          preferred: [],
          disliked: [],
          pending: [],
          unvoted: []
        };
        for (_i = 0, _len = docs.length; _i < _len; _i++) {
          name = docs[_i];
          score = (_ref = name.votes) != null ? _ref[voter] : void 0;
          simpleName = _.pick(name, '_id', 'name');
          if (score === void 0) {
            results.unvoted.push(simpleName);
          } else {
            if (score > 0) {
              results.preferred.push(simpleName);
            } else if (score < 0) {
              results.disliked.push(simpleName);
            } else {
              results.pending.push(simpleName);
            }
          }
        }
        return cb(null, results);
      });
    };

    NameRoute.prototype.handleVoterVoteFor = function(req, res) {
      var id, queryClouse, score, updateClouse, voter, _ref,
        _this = this;
      voter = req.params.voter;
      _ref = req.query, id = _ref.id, score = _ref.score;
      queryClouse = {
        _id: id
      };
      updateClouse = {};
      updateClouse["votes." + voter] = parseInt(score, 10);
      return NameCandidate.findOneAndUpdate(queryClouse, updateClouse, function(err, numberAffected) {
        if (err) {
          return res.send(500, err);
        } else {
          console.log(numberAffected);
          return res.json(200, numberAffected);
        }
      });
    };

    return NameRoute;

  })();

}).call(this);
